### ISSUE TITLE
Finalise steering column design

### ISSUE THREAD

**Issue by Juliankautsch** [Juliankautsch/lfrt#146]

**Comment by Maciejgrybko** [comment]
Link to UJ:
https://uk.rs-online.com/web/p/universal-joints/7906712/?relevancy-data=636F3D3126696E3D4931384E525353746F636B4E756D626572266C753D656E266D6D3D6D61746368616C6C26706D3D5E285C647B362C377D5B4161426250705D297C285C647B337D5B5C732D2F255C2E2C5D5C647B332C347D5B4161426250705D3F292426706F3D3126736E3D592673723D2673743D52535F53544F434B5F4E554D4245522677633D4E4F4E45267573743D3739302D36373132267374613D3739303637313226
