### ISSUE TITLE
Check material for headrest

### ISSUE THREAD

**Issue by Maciejgrybko** [Juliankautsch/lfrt#151]
Go to motorsport website and check what foam it can be made of.
Once done, discuss with Alan.

**Comment by sijinvsaji** [comment]
I think, this is it - https://www.amazon.co.uk/BSCI-Approved-Padding-diameter-Black/dp/B00DHLPXJW 

It meets the FIA criteria - Just waiting for Alan to approve it.

**Comment by sijinvsaji** [comment]
Waiting for @mn16mg to reply
