### ISSUE TITLE
Manufacture differential brakets

### ISSUE THREAD

**Issue by Juliankautsch** [Juliankautsch/lfrt#96]

**Comment by Juliankautsch** [comment]
@VagosZacharias @mn15kk  I am not sure but haven't we done these yet?

**Comment by VagosZacharias** [comment]
@Juliankautsch We've been discussing it today. We are still not sure if the ones we have will be sufficient to fit the chain properly around the tube. They most probably will be ok though. It's already too late to get them CNC at this point
